spring.application.name=my-react-service
server.port=8080

spring.datasource.url=${SQLSERVER_URL:jdbc:sqlserver://DESKTOP-VKNSMP5:1433;databaseName=calculator_db;trustServerCertificate=true;encrypt=true}
spring.datasource.username=${SQLSERVER_USERNAME:sa}
spring.datasource.password=${SQLSERVER_PASSWORD:Pass1975#}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
