spring.application.name=calculator-service
server.port=8080

spring.datasource.url=${SQLSERVER_URL:jdbc:sqlserver://DESKTOP-VKNSMP5:1433;databaseName=calculator_db;integratedSecurity=true;trustServerCertificate=true;encrypt=true}
spring.datasource.username=${SQLSERVER_USERNAME:}
spring.datasource.password=${SQLSERVER_PASSWORD:}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
